version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    versioning-strategy: "increase"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      all-dependencies:
        patterns:
          - "*"  # This groups all dependencies into one PR
